name: Test for creating a pull request

# PR作成or再作成時
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # - name: Build and run Docker Compose
      #   run: docker-compose -f core/docker-compose.yml run --rm web
      - name: Build and run Docker Compose
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          docker-compose -f core/docker-compose.yml build --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=type=local,src=/tmp/.buildx-cache
          docker-compose -f core/docker-compose.yml run --rm web

      - name: Save Docker cache
        if: success()
        run: |
          mkdir -p /tmp/.buildx-cache
          docker save myimage | gzip > /tmp/.buildx-cache/myimage.tar.gz

